import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppHeader } from "@/features/header/AppHeader";
import { getHeaderDataForUser } from "@/infra/header/getHeaderData";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const userId = process.env.DEV_USER_ID;

  const header = userId
    ? await getHeaderDataForUser(userId).catch((err) => {
        console.error("Failed to load header data", err);
        return null;
      })
    : null;

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[var(--color-background)]`}>
        <div className="min-h-screen">
          {header && <AppHeader data={header} />}
          {children}
        </div>
      </body>
    </html>
  );
}
